spring:
  application:
    name: pedidos-ms
  datasource:
    url: jdbc:mysql://localhost:3306/alurafood-pedidos?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: alurafood
    password: alurafood

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}

server:
  port: 0