spring:
  application:
    name: avaliacao-ms
  rabbitmq:
    host: localhost
    port: 5672
    username: alurafood
    password: alurafood
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 4
          initial-interval: 1000
          multiplier: 2
          max-interval: 30000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

server:
  port: 0